### ISSUE TITLE
Support for TemplatedEmail

### ISSUE THREAD

**Issue by benr77** [fusonic/php-messenger-mailer-bundle#1]
Hello. Would it be possible to also support extending from `TemplatedEmail` as well or instead of the default `Email` class? 

It's very common to use Twig templates for email content and currently if we do `new AttachmentEmail()` we immediately lose all the Twig integration that Symfony provides.

Thanks!

**Comment by arjanfrans** [comment]
That's a good idea. I will take a look at it!

**Comment by arjanfrans** [comment]
It will be included in the next verion. Either this week or next week.

**Comment by arjanfrans** [comment]
@benr77 Just released a new version, you can now use the `TemplatedAttachmentEmail` class for this.

**Comment by benr77** [comment]
Great stuff thank you for your efforts!
